
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNDAzOTY0","is_bot":false,"login":"aardvarkzone","name":"Advait Arumugam"},"headRefName":"Advait-ArticlesTable","number":49,"title":"Add Articles Controller and Tests ","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/49"},{"author":{"id":"MDQ6VXNlcjkxNDk5MjI5","is_bot":false,"login":"lpullela","name":""},"headRefName":"Laya-Organization","number":48,"title":"Laya organization","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/48"},{"author":{"id":"U_kgDOBX3XaQ","is_bot":false,"login":"bonniehuynh","name":""},"headRefName":"Bonnie-RecRequestTable","number":43,"title":"Bonnie rec request table","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/43"}]
