
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjY2ODkyOTQw","is_bot":false,"login":"konarkv","name":""},"headRefName":"Konark-DiningCommons","number":52,"title":"initial and hopefully final commit","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/52"},{"author":{"id":"MDQ6VXNlcjQwNDAzOTY0","is_bot":false,"login":"aardvarkzone","name":"Advait Arumugam"},"headRefName":"Advait-ArticlesTable","number":51,"title":"Articles Controller / Tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/51"},{"author":{"id":"MDQ6VXNlcjQwNDAzOTY0","is_bot":false,"login":"aardvarkzone","name":"Advait Arumugam"},"headRefName":"Advait-readme","number":50,"title":"Update README.md","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/50"},{"author":{"id":"MDQ6VXNlcjkxNDk5MjI5","is_bot":false,"login":"lpullela","name":""},"headRefName":"Laya-Organization","number":48,"title":"Laya organization","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/48"}]
