
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-4pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-4pm-3
pull_requests: [{"author":{"id":"U_kgDOBdHRmA","is_bot":false,"login":"srambhatla30","name":""},"headRefName":"Sid-HelpRequest","number":45,"title":"Merge sid help request","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/45"},{"author":{"id":"U_kgDOBXuwTQ","is_bot":false,"login":"hugolin0","name":""},"headRefName":"Hugo-MenuItemReviewController","number":44,"title":"Add MenuItemReview Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/44"},{"author":{"id":"U_kgDOBX3XaQ","is_bot":false,"login":"bonniehuynh","name":""},"headRefName":"Bonnie-RecRequestTable","number":43,"title":"Bonnie rec request table","url":"https://github.com/ucsb-cs156-w24/team02-w24-4pm-3/pull/43"}]
